name: CI Pipeline

# Configuración de triggers: se ejecuta en pushes y PRs a la rama main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest

    # Configuración de estrategia para permitir fallos rápidos
    strategy:
      matrix:
        node-version: [20.x]
      fail-fast: false

    steps:
      # Paso 1: Checkout del código
      - uses: actions/checkout@v4

      # Paso 2: Configuración de caché para optimizar tiempos de construcción
      - name: Cache bun modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Paso 3: Instalación de Bun (runtime JavaScript)
      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      # Paso 4: Instalación de dependencias
      - name: Install dependencies
        run: bun install

      # Verificaciones de calidad del código
      - name: Run linter
        run: bun run lint

      # Verificaciones de seguridad
      # - name: Security audit for dependencies
        # run: bun pm audit

      # Verificaciones de dependencias
      - name: Check for dependency errors
        run: bun pm ls --omit=dev
